### ISSUE TITLE
You're not here at Tokyo Rubyists October

### ISSUE THREAD

**Issue by corps** [0cjs/sedoc#1]
Hey,

So I'm leaving at the end of the month, and I was hoping to grab you for a chat at my last Tokyo Rubyists meetup this month!  But you didn't make it.  :(

Are you around this weekend for a drink?  If not, that's cool.

Zach

**Comment by 0cjs** [comment]
@corps: I'd love to meet up; get in touch with me either via private message to my [0cjs account on Gitter](https://gitter.im/0cjs) or, failing that, the e-mail address on my [GitHub profile page](https://github.com/0cjs) (but the latter won't get to me nearly as fast).
